name: Integración Continua

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener código del repositorio
        uses: actions/checkout@v3

      - name: Validar código (simulado)
        run: echo "Todo correcto. Archivos detectados correctamente."
